### ISSUE TITLE
Error parsing commandline module path in Windows

### ISSUE THREAD

**Issue by gimmi** [mozilla/rhino#10]
The command:

<pre>
java -cp js.jar org.mozilla.javascript.tools.shell.Main -modules "C:\Users\Gimmi\Sources\jsmake\"
</pre>

Throws this rerror on Windows:

<pre>
Exception in thread "main" java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in path at index 5: Users\Gimmi\Sources\jsmake
        at org.mozilla.javascript.tools.shell.Global.installRequire(Global.java:182)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:131)
        at org.mozilla.javascript.Context.call(Context.java:521)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)
Caused by: java.net.URISyntaxException: Illegal character in path at index 5: Users\Gimmi\Sources\jsmake
        at java.net.URI$Parser.fail(URI.java:2809)
        at java.net.URI$Parser.checkChars(URI.java:2982)
        at java.net.URI$Parser.parseHierarchical(URI.java:3066)
        at java.net.URI$Parser.parse(URI.java:3024)
        at java.net.URI.<init>(URI.java:578)
        at org.mozilla.javascript.tools.shell.Global.installRequire(Global.java:170)
        ... 5 more
</pre>

This command instead seems to work (note the "\" replaced with "/"):

<pre>
java -cp js.jar org.mozilla.javascript.tools.shell.Main -modules "file:///C:/Users/Gimmi/Sources/jsmake/"
</pre>

**Comment by p-bakker** [comment]
As the module directory needs to be an URI it is expected that `file:///C:/Users/Gimmi/Sources/jsmake/` works and `C:\Users\Gimmi\Sources\jsmake\` doesn't, as the later isn't a URI, see https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

Leaving this open and tagged with docs to include this in the cods
