### ISSUE TITLE
`spotless` formatter breaks the build with recent JDKs

### ISSUE THREAD

**Issue by carlosame** [mozilla/rhino#1036]
The `spotless` plugin breaks the build with recent JDKs (at least JDK 16 and 17):
```console
> Task :spotlessJava FAILED
Step 'google-java-format' found problem in 'benchmarks\org\mozilla\javascript\benchmarks\BuiltinBenchmark.java':
null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.diffplug.spotless.java.GoogleJavaFormatStep$State.lambda$createFormat$1(GoogleJavaFormatStep.java:159)
        at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:32)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:201)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:188)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:71)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:57)
[...]
Caused by: java.lang.IllegalAccessError: class com.google.googlejavaformat.java.JavaInput (in unnamed module @0x1ae72560) cannot access class com.sun.tools.javac.parser.Tokens$TokenKind (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.parser to unnamed module @0x1ae72560
        at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:349)
        at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:334)
        at com.google.googlejavaformat.java.JavaInput.<init>(JavaInput.java:276)
        at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:280)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:267)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:233)
        ... 148 more
```
This is a known `spotless` issue, diffplug/spotless#834 and they have a workaround (see https://github.com/diffplug/spotless/issues/834#issuecomment-819118761) that breaks Java 8. I have not found a way to conditionally apply the workaround only for JDKs later than 8, so I suggest disabling the plugin for modular JDKs.

I can provide a PR that disables `spotless` for modular JDKs, unbreaking that part of the build (yes the tests also fail with Java 17 but that's a different issue). Unless there are other suggestions.

Also, the Gradle wrapper should be upgraded to 7.2 (can do that in the PR as well), otherwise:
```console
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\***\rhino\build.gradle'

* What went wrong:
Could not compile build file 'C:\***\rhino\build.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 61

  java.lang.IllegalArgumentException: Unsupported class file major version 61
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:189)
```
Is it fine to try to unbreak the build for Java 17, or is the project sticking to Java 8?

**Comment by carlosame** [comment]
I opened a PR to fix this issue. It disables the spotless tasks for all modular JDKs, although it could be changed to only JDKs > 15 (I looked at the CI results and it seems that versions up to 15 are not affected).

**Comment by tonygermano** [comment]
There are no plans to stop supporting Java 8 in the near future. Rather than disabling the spotless tasks, which I think would be undesirable, can we just put in the README how to add the workaround if you are building with java 16+ until spotless has a more permanent fix or we do finally drop java 8 support?

**Comment by carlosame** [comment]
> just put in the README how to add the workaround if you are building with java 16+

This assumes that everybody is going to read the full README before building, and then associate the error that they are seeing with the issue that the README mentions. Instead, my PR prints a warning with the URL to the solution, which seems more helpful to me (I also included a mention in the README).

And disabling the problematic task makes it easier to use Java 17 in the current Rhino CI (BTW there are other pending bugs like #1039 and the spotBugs problems that have no issue opened yet AFAIK).

> or we do finally drop java 8 support

Java 8 is [supported until May 2026](https://adoptium.net/support.html#roadmap), and it seems reasonable that libraries support it as long as they are able to. However, that does not mean that at some point this project could require Java 11 or later to be built (while still producing Java 8 binaries). Not that I see a compelling reason to do that now, though.
