### ISSUE TITLE
Modularisation issue with `JsTestsTest`

### ISSUE THREAD

**Issue by carlosame** [mozilla/rhino#1039]
With modular JDKs, test `JsTestsTest` produces either errors or warnings:

- With Java 11:
```console
> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mozilla.javascript.JavaMembers (file:/C:/***/rhino/buildGradle/classes/java/main/) to field javax.swing.table.AbstractTableModel.listenerList
WARNING: Please consider reporting this to the maintainers of org.mozilla.javascript.JavaMembers
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
- Java 16 or 17:
```console
> Task :test

org.mozilla.javascript.tests.JsTestsTest > testJsTestsInterpreted STANDARD_ERROR
    org.mozilla.javascript.EvaluatorException: error instantiating (Wrapped java.lang.reflect.InaccessibleObjectException: Unable to make field protected javax.swing.event.EventListenerList javax.swing.table.AbstractTableModel.listenerList accessible: module java.desktop does not "opens javax.swing.table" to unnamed module @21b8d17c (jstest input: 437988.jstest#7)): class javax.swing.table.AbstractTableModel is interface or abstract (jstest input: 437988.jstest#7)
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:907)
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:963)
        at org.mozilla.javascript.Context.reportRuntimeErrorById(Context.java:914)
        at org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:200)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1933)
        at script(jstest input: 437988.jstest:7)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1053)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3866)
        at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:103)
        at org.mozilla.javascript.Context.evaluateString(Context.java:1137)
        at org.mozilla.javascript.drivers.JsTestsBase.runJsTest(JsTestsBase.java:46)
        at org.mozilla.javascript.drivers.JsTestsBase.runJsTests(JsTestsBase.java:67)
        at org.mozilla.javascript.tests.JsTestsTest.runJsTests(JsTestsTest.java:27)
        at org.mozilla.javascript.tests.JsTestsTest.testJsTestsInterpreted(JsTestsTest.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

org.mozilla.javascript.tests.JsTestsTest > testJsTestsInterpreted STANDARD_OUT
    FAILED

org.mozilla.javascript.tests.JsTestsTest > testJsTestsInterpreted FAILED
    org.mozilla.javascript.EvaluatorException at JsTestsTest.java:27
```
There are two alternative approaches to fix this kind of issues: a full modularisation or adding JVM arguments as a workaround.

A full modularisation would imply changing the packaging of this project, as well as the source layout as mentioned in #870. Something that could be decided in the future, but definitely not appropriate for a 1.7.* release. So I'm preparing a PR with the JVM argument workaround.

**Comment by tonygermano** [comment]
Related to https://github.com/mozilla/rhino/issues/462
