### ISSUE TITLE
Found some potential NPEs in `Parser.java` and patch PR is on the road.

### ISSUE THREAD

**Issue by MaxisTekfield** [mozilla/rhino#1095]
I've found running following script in rhino-1.7.12 can cause NPE.

```
js> let [a, b] = [1, 2];
js> let [c, c] = [1, 2];
Exception in thread "main" java.lang.NullPointerException
	at org.mozilla.javascript.Parser.addError(Parser.java:234)  // Maybe the line# is not correct because of my local modifications.
	at org.mozilla.javascript.Parser.defineSymbol(Parser.java:2254)
	at org.mozilla.javascript.Parser.destructuringArray(Parser.java:4062)
	at org.mozilla.javascript.Parser.destructuringAssignmentHelper(Parser.java:4007)
	at org.mozilla.javascript.Parser.createDestructuringAssignment(Parser.java:3982)
	at org.mozilla.javascript.IRFactory.transformVariableInitializers(IRFactory.java:1238)
	at org.mozilla.javascript.IRFactory.transformVariables(IRFactory.java:1201)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:223)
	at org.mozilla.javascript.IRFactory.transformScript(IRFactory.java:1041)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:191)
	at org.mozilla.javascript.IRFactory.transformTree(IRFactory.java:117)
	at org.mozilla.javascript.Context.parse(Context.java:2587)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2521)
	at org.mozilla.javascript.Context.compileString(Context.java:1525)
	at org.mozilla.javascript.Context.compileString(Context.java:1514)
	at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:494)
	at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:181)
	at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:101)
	at org.mozilla.javascript.Context.call(Context.java:559)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.tools.shell.Main.exec(Main.java:163)
	at org.mozilla.javascript.tools.shell.Main.main(Main.java:138)
```

Obviously Parser.addError miss checking ts agaist to null. And more potential NPEs can be found in following methods:
1. void addWarning(String messageId, String messageArg, int position, int length)
2. void addError(String messageId)
3. void addError(String messageId, String messageArg)
4. void addError(String messageId, int c)

Some of them are fixed in master branch, but some not (eg. 1st/2nd/4th). I'd like to fixed these potential NPEs and will submit a PR in the next few days.

One more thing. Since under these NPE situations we can't get correct position and length, should I set them to `0` or `1`? Which is better?
I've found both `0` and `1` are used in the latest code.
- void addError(String messageId, String messageArg)  uses `0`
- void reportError(String messageId, String messageArg)  uses `1`

**Comment by tuchida** [comment]
-  #967

I think it's wrong that `Parser.addError` is called from `IRFactory`.

**Comment by MaxisTekfield** [comment]
I absolute agree that `IRFactory` inheriting from `Parser` is not a good pattern. Some problems can only be detected by `IRFactory` but `IRFactory` has no TokenStream cause these NPEs. Some refactors are need to take place. I think it's going to take bundle of time to do refactorings.
Maybe short way - fixing these potential NPEs is also needed.
