### ISSUE TITLE
Rhino 1.7.14 is not available under Android SDK 21

### ISSUE THREAD

**Issue by ylk2534246654** [mozilla/rhino#1156]
Rhino 1.7.13 worked well before.
Stack trace:
`
java.lang.NoClassDefFoundError: org.mozilla.javascript.NativeError$$ExternalSyntheticLambda4
        at org.mozilla.javascript.NativeError.fillConstructorProperties(NativeError.java:82)
        at org.mozilla.javascript.IdScriptableObject.exportAsJSClass(IdScriptableObject.java:725)
        at org.mozilla.javascript.NativeError.init(NativeError.java:38)
        at org.mozilla.javascript.ScriptRuntime.initSafeStandardObjects(ScriptRuntime.java:162)
        at org.mozilla.javascript.ScriptRuntime.initStandardObjects(ScriptRuntime.java:300)
        at org.mozilla.javascript.Context.initStandardObjects(Context.java:1076)
        at org.mozilla.javascript.Context.initStandardObjects(Context.java:980)
`

**Comment by p-bakker** [comment]
Duplicate of #1149

**Comment by p-bakker** [comment]
Also see #1149

**Comment by p-bakker** [comment]
As this supposedly is a duplicate of #1149, which has been resolved, I'm gonna close this issue as well
