### ISSUE TITLE
Java keywords not allowed in JavaScript?

### ISSUE THREAD

**Issue by josdejong** [mozilla/rhino#127]
I have a weird error and I'm not sure where this comes from. It looks like when using the RhinoScriptEngine that comes with Java, it is not allowed to use [Java keywords](http://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html) in your JavaScript:

``` java
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

public class Test {
    public static void main(String[] args) throws ScriptException {
        ScriptEngineManager manager = new ScriptEngineManager ();
        ScriptEngine engine = manager.getEngineByName ("js");

        engine.eval("var obj = {};");
        engine.eval("obj.foo = 2;");        // OK
        engine.eval("obj.boolean = 2;");    // error
        engine.eval("obj.char = 2;");       // error
        engine.eval("obj.long = 2;");       // error
        engine.eval("obj.transient = 2;");  // error
        // etc... 
        // Java keywords not allowed in JavaScript?!
    }
}
```

Gives the following error:

```
Exception in thread "main" javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: missing name after . operator (<Unknown source>#1) in <Unknown source> at line number 1
    at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:224)
    at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:240)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
    at Test.main(Test.java:12)
Caused by: sun.org.mozilla.javascript.internal.EvaluatorException: missing name after . operator (<Unknown source>#1)
    at sun.org.mozilla.javascript.internal.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:109)
    at sun.org.mozilla.javascript.internal.DefaultErrorReporter.error(DefaultErrorReporter.java:96)
    at sun.org.mozilla.javascript.internal.Parser.addError(Parser.java:231)
    at sun.org.mozilla.javascript.internal.Parser.addError(Parser.java:209)
    at sun.org.mozilla.javascript.internal.Parser.reportError(Parser.java:266)
    at sun.org.mozilla.javascript.internal.Parser.reportError(Parser.java:253)
    at sun.org.mozilla.javascript.internal.Parser.reportError(Parser.java:246)
    at sun.org.mozilla.javascript.internal.Parser.propertyAccess(Parser.java:2644)
    at sun.org.mozilla.javascript.internal.Parser.memberExprTail(Parser.java:2520)
    at sun.org.mozilla.javascript.internal.Parser.memberExpr(Parser.java:2495)
    at sun.org.mozilla.javascript.internal.Parser.unaryExpr(Parser.java:2369)
    at sun.org.mozilla.javascript.internal.Parser.mulExpr(Parser.java:2292)
    at sun.org.mozilla.javascript.internal.Parser.addExpr(Parser.java:2274)
    at sun.org.mozilla.javascript.internal.Parser.shiftExpr(Parser.java:2253)
    at sun.org.mozilla.javascript.internal.Parser.relExpr(Parser.java:2226)
    at sun.org.mozilla.javascript.internal.Parser.eqExpr(Parser.java:2196)
    at sun.org.mozilla.javascript.internal.Parser.bitAndExpr(Parser.java:2183)
    at sun.org.mozilla.javascript.internal.Parser.bitXorExpr(Parser.java:2170)
    at sun.org.mozilla.javascript.internal.Parser.bitOrExpr(Parser.java:2157)
    at sun.org.mozilla.javascript.internal.Parser.andExpr(Parser.java:2144)
    at sun.org.mozilla.javascript.internal.Parser.orExpr(Parser.java:2131)
    at sun.org.mozilla.javascript.internal.Parser.condExpr(Parser.java:2107)
    at sun.org.mozilla.javascript.internal.Parser.assignExpr(Parser.java:2076)
    at sun.org.mozilla.javascript.internal.Parser.expr(Parser.java:2053)
    at sun.org.mozilla.javascript.internal.Parser.nameOrLabel(Parser.java:1811)
    at sun.org.mozilla.javascript.internal.Parser.statementHelper(Parser.java:1075)
    at sun.org.mozilla.javascript.internal.Parser.statement(Parser.java:944)
    at sun.org.mozilla.javascript.internal.Parser.parse(Parser.java:569)
    at sun.org.mozilla.javascript.internal.Parser.parse(Parser.java:531)
    at sun.org.mozilla.javascript.internal.Context.compileImpl(Context.java:2438)
    at sun.org.mozilla.javascript.internal.Context.compileReader(Context.java:1355)
    at sun.org.mozilla.javascript.internal.Context.compileReader(Context.java:1327)
    at sun.org.mozilla.javascript.internal.Context.evaluateReader(Context.java:1166)
    at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:214)
    ... 3 more
```

This does happen when using Java 7 Oracle. It does _not_ happen when using Java 6 OpenJDK or Java 7 OpenJDK. And it does _not_ happen when using the standalone [Rhino js.jar](https://developer.mozilla.org/en-US/docs/Rhino/Download_Rhino) file.

**Comment by p-bakker** [comment]
Closing this as Rhino is not longer bundled with Java and this issue doesn't occur in the stand-alone Rhino
