### ISSUE TITLE
ClassFileWriter out of range index processing 2.4.3 jshint-rhino.js

### ISSUE THREAD

**Issue by pd40** [mozilla/rhino#130]
From https://github.com/jshint/jshint/issues/1422 using src 
https://raw2.github.com/jshint/jshint/2.x/dist/jshint-rhino.js

Running a 2.3+ version of jshint-rhino.js through 1.7R5 causes the stack trace below processing a large array of constant values (line 28779). 

```
$ rhino jshint-rhino.js 
Exception in thread "main" java.lang.IllegalArgumentException: out of range index
    at org.mozilla.classfile.ClassFileWriter.add(ClassFileWriter.java:579)
    at org.mozilla.classfile.ClassFileWriter.addLoadConstant(ClassFileWriter.java:676)
    at org.mozilla.classfile.ClassFileWriter.addPush(ClassFileWriter.java:929)
    at org.mozilla.javascript.optimizer.Codegen.pushNumberAsObject(Codegen.java:1087)
    at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2238)
    at org.mozilla.javascript.optimizer.BodyCodegen.visitArrayLiteral(Codegen.java:3085)
    at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2318)
    at org.mozilla.javascript.optimizer.BodyCodegen.visitSetProp(Codegen.java:5025)
    at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2592)
    at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:2033)
    at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1858)
    at org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(Codegen.java:1289)
    at org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:306)
    at org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:166)
    at org.mozilla.javascript.optimizer.Codegen.compile(Codegen.java:75)
    at org.mozilla.javascript.Context.compileImpl(Context.java:2377)
    at org.mozilla.javascript.Context.compileString(Context.java:1335)
    at org.mozilla.javascript.Context.compileString(Context.java:1324)
    at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:591)
    at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:556)
    at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:527)
    at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:176)
    at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:100)
    at org.mozilla.javascript.Context.call(Context.java:489)
    at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
    at org.mozilla.javascript.tools.shell.Main.exec(Main.java:158)
    at org.mozilla.javascript.tools.shell.Main.main(Main.java:136)
```

**Comment by gbrail** [comment]
This works for me on the latest code from "master:"

https://github.com/jshint/jshint.git
cd jshint
npm install
npm run build
cd dist
rhino jshint-rhino.js ../tests/unit/fixtures/asi.js

I can replace "rhino" with "java -jar js.jar" (given "js.jar" from the latest Rhino build) and it works as well.

Is there something else that we should try?

**Comment by rbri** [comment]
alt least with the fix for the code generation falling back to the interpreter, this should be solved
