### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError: org.mozilla.javascript.NativeError$$ExternalSyntheticLambda2 android 6.0.1

### ISSUE THREAD

**Issue by sascha-hack** [mozilla/rhino#1421]
Getting this on android 6.0.1

```
Fatal Exception: java.lang.NoClassDefFoundError: org.mozilla.javascript.NativeError$$ExternalSyntheticLambda2
       at org.mozilla.javascript.NativeError.fillConstructorProperties(NativeError.java:82)
       at org.mozilla.javascript.IdScriptableObject.exportAsJSClass(IdScriptableObject.java:725)
       at org.mozilla.javascript.NativeError.init(NativeError.java:38)
       at org.mozilla.javascript.ScriptRuntime.initSafeStandardObjects(ScriptRuntime.java:162)
       at org.mozilla.javascript.ScriptRuntime.initStandardObjects(ScriptRuntime.java:300)
       at org.mozilla.javascript.Context.initStandardObjects(Context.java:1076)
       at org.mozilla.javascript.ImporterTopLevel.initStandardObjects(ImporterTopLevel.java:73)
       at org.mozilla.javascript.ImporterTopLevel.<init>(ImporterTopLevel.java:57)
       at com.sun.script.javascript.RhinoTopLevel.<init>(RhinoTopLevel.java:56)
       at com.sun.script.javascript.RhinoScriptEngine.<init>(RhinoScriptEngine.java:188)
       at com.sun.script.javascript.RhinoScriptEngineFactory.getScriptEngine(RhinoScriptEngineFactory.java:78)
       at javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:225)
```

**Comment by gbrail** [comment]
Sorry, it's hard to tell from the stack trace what the problem might be. To start with, what version of Rhino are you using? What did you do in order to make this stack trace appear? Most people in this community don't have a way to test something on Android, so is there another way that we can reproduce this?

**Comment by p-bakker** [comment]
Closing as there has been no follow-up by the reporter.

Feel free to reopen with more information
