### ISSUE TITLE
JavaAdapter unavailable in Android environment on upstream rhino

### ISSUE THREAD

**Issue by naijun0403** [mozilla/rhino#1634]
## Environment
- Android: 14
- rhino: 1.7.16-SNAPSHOT (based on b08de525f3daefa9800a509a5e5a5b27848da7ff commit)

## Code
```js
const timer = new java.util.TimerTask({ run: () => {} });
```

## What's expected
Android does not support the jvm's .class file format, so you need to use InterfaceAdapter to create a proxy and provide similar functionality instead of modifying the bytecode directly (works fine until rhino 1.7.15)

![Screenshot_20240919_215216](https://github.com/user-attachments/assets/8660e7f3-9e7c-42f8-88da-97904dd9e676)

## Actual behavior
throw this error

```
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  java.lang.ExceptionInInitializerError
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.JavaAdapter.createAdapterCode(JavaAdapter.java:328)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.JavaAdapter.getAdapterClass(JavaAdapter.java:312)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:169)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:87)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:85)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:411)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:173)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:2052)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1109)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:87)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:383)
2024-09-19 21:45:34.778 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:4029)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:100)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	at com.xfl.msgbot.script.api.modern.ScriptManager$Companion.initializeScript(ScriptManager.kt:261)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	at com.xfl.msgbot.script.ScriptManagerCompat$Companion.initializeScript(ScriptManagerCompat.kt:151)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	at com.xfl.msgbot.script.ScriptManagerCompat$Companion.initializeScript$default(ScriptManagerCompat.kt:137)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	at com.xfl.msgbot.application.activity.ScriptListAdapter.onBindViewHolder$lambda$7$lambda$6(ScriptListAdapter.kt:151)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	at com.xfl.msgbot.application.activity.ScriptListAdapter.$r8$lambda$-YWf-SZ-WLN1cmvdH5QnVuOnftM(Unknown Source:0)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	at com.xfl.msgbot.application.activity.ScriptListAdapter$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	at java.lang.Thread.run(Thread.java:1012)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	at org.mozilla.classfile.ClassFileWriter.<clinit>(ClassFileWriter.java:4376)
2024-09-19 21:45:34.779 12181-12447 System.err              com.xfl.msgbot                       W  	... 20 more
```

## The likely cause of the issue
Since the 1.7.15 release, there have been quite a few changes to the IRFactory and Parser. This is probably the cause.

**Comment by naijun0403** [comment]
fixed by bb15f768b8b40d337087934742c1860b69ece49d
