### ISSUE TITLE
NullPointerException in CodeGenerator

### ISSUE THREAD

**Issue by digulla** [mozilla/rhino#194]
I came up with a simple test case which throws NPE in `CodeGenerator`:

    @Test
    public void testCompileExpression() throws Exception {
        String expression = "row[\"COL_Col1\"]";
        CompilerEnvirons compilerEnv = new CompilerEnvirons();
        Parser p = new Parser( compilerEnv, compilerEnv.getErrorReporter() );
        AstRoot script = p.parse( expression, null, 0 );
        
        Interpreter compiler = new Interpreter( );
        Object compiledOb = compiler.compile( compilerEnv, script, null, false );
        assertNotNull( compiledOb );
    }

If you run the test, you get an NPE:

	java.lang.NullPointerException
	    at org.mozilla.javascript.CodeGenerator.visitExpression(CodeGenerator.java:497)
	    at org.mozilla.javascript.CodeGenerator.visitStatement(CodeGenerator.java:383)
	    at org.mozilla.javascript.CodeGenerator.visitStatement(CodeGenerator.java:276)
	    at org.mozilla.javascript.CodeGenerator.generateICodeFromTree(CodeGenerator.java:113)
	    at org.mozilla.javascript.CodeGenerator.compile(CodeGenerator.java:83)
	    at org.mozilla.javascript.Interpreter.compile(Interpreter.java:194)

This is probably related to the new AST API and bug #116 

The source of the problem is that many AST nodes return null for `getFirstChild()` but the visit* methods depend on this.

**Comment by digulla** [comment]
Found it; I have to process the "raw" AST tree with `IRFactory`:

    IRFactory irf = new IRFactory(compilerEnv, compilerEnv.getErrorReporter());
    ScriptNode tree = irf.transformTree(ast);

Then it works.
