### ISSUE TITLE
[Request] Android support

### ISSUE THREAD

**Issue by F43nd1r** [mozilla/rhino#211]
Rhino works fine on Android with one big drawback: JavaAdapter can't be used, because it relies on Java bytecode, while android runs Dalvik bytecode.
Has anyone ever tried to create a version which removes this drawback in any way?
If not, can somebody do this or point me in a direction where I could start with this?

**Comment by eshepelyuk** [comment]
As far as I know, this class doesn't generate any bytecode on its own. Is it what you have problems with ?
About bytecode generation - maybe you could try to use optmization level `-1`,  so Rhino will not try to generate any bytecode.

**Comment by eshepelyuk** [comment]
Maybe you could try to use optimization level `-1`, so Rhino will not try to generate any bytecode ? 
It will probably decrease performance, but maybe in your case it will not be a stopper.

**Comment by F43nd1r** [comment]
Rhino does only work on android with optimization level set to -1, so this is already set.

here is the logcat of a simple test script for JavaAdapter:

java.lang.UnsupportedOperationException: can't load this type of class file
at java.lang.ClassLoader.defineClass(ClassLoader.java:288)
at org.mozilla.javascript.v.a(DefiningClassLoader.java:27)
at org.mozilla.javascript.JavaAdapter.a(JavaAdapter.java:333)
at org.mozilla.javascript.JavaAdapter.a(JavaAdapter.java:173)
at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:86)
at org.mozilla.javascript.ah.a(IdFunctionObject.java:97)
at org.mozilla.javascript.b.a(BaseFunction.java:343)
at org.mozilla.javascript.ao.a(Interpreter.java:1519)
at org.mozilla.javascript.ao.a(Interpreter.java:815)
at org.mozilla.javascript.an.a(InterpretedFunction.java:109)
at org.mozilla.javascript.o.a(ContextFactory.java:394)
at org.mozilla.javascript.dn.a(ScriptRuntime.java:3091)
at org.mozilla.javascript.l.a(Context.java:1172)
at org.mozilla.javascript.l.a(Context.java:1139)
at net.pierrox.lightning_launcher.c.b.a(ScriptExecutor.java:498)
at net.pierrox.lightning_launcher.activities.ar.run(Dashboard.java:1702)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5086)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)

**Comment by gbrail** [comment]
Yes -- Rhino generates "regular" Java bytecode, so yes, if you want to be
in Dalvik or Art, that'll be the wrong kind of byte code. Generating a
different kind of bytecode would require someone to write a new back end
for Rhino (and since it only has one back end, there would be some
refactoring required to make that happen).



On Mon, Jun 29, 2015 at 11:53 AM, F43nd1r <notifications@github.com> wrote:

> Rhino does only work on android with optimization level set to -1, so this
> is already set.
>
> here is the logcat of a simple test script for JavaAdapter:
>
> java.lang.UnsupportedOperationException: can't load this type of class file
> at java.lang.ClassLoader.defineClass(ClassLoader.java:288)
> at org.mozilla.javascript.v.a(DefiningClassLoader.java:27)
> at org.mozilla.javascript.JavaAdapter.a(JavaAdapter.java:333)
> at org.mozilla.javascript.JavaAdapter.a(JavaAdapter.java:173)
> at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:86)
> at org.mozilla.javascript.ah.a(IdFunctionObject.java:97)
> at org.mozilla.javascript.b.a(BaseFunction.java:343)
> at org.mozilla.javascript.ao.a(Interpreter.java:1519)
> at org.mozilla.javascript.ao.a(Interpreter.java:815)
> at org.mozilla.javascript.an.a(InterpretedFunction.java:109)
> at org.mozilla.javascript.o.a(ContextFactory.java:394)
> at org.mozilla.javascript.dn.a(ScriptRuntime.java:3091)
> at org.mozilla.javascript.l.a(Context.java:1172)
> at org.mozilla.javascript.l.a(Context.java:1139)
> at net.pierrox.lightning_launcher.c.b.a(ScriptExecutor.java:498)
> at net.pierrox.lightning_launcher.activities.ar.run(Dashboard.java:1702)
> at android.os.Handler.handleCallback(Handler.java:733)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:136)
> at android.app.ActivityThread.main(ActivityThread.java:5086)
> at java.lang.reflect.Method.invokeNative(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:515)
> at
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
> at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
> at dalvik.system.NativeStart.main(Native Method)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/211#issuecomment-116795466>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
<http://iloveapis.com/>

**Comment by F43nd1r** [comment]
I am just wondering why everything else - even implementing interfaces - works,  but the JavaAdapter doesn't....

**Comment by gbrail** [comment]
The JavaAdapter also generates bytecode to do its job. It uses the same ClassFileWriter as the regular code generation, so that generates bytecode that's compatible with Java and apparently not with Dalvik. So depending on how different the bytecodes are, we'd have to create a new ClassFileWriter for different VMs.

**Comment by F43nd1r** [comment]
I found a very interesting project: Dexmaker (https://github.com/crittercism/dexmaker). I tried to replace the current classfilewriter with a wrapper around the dexmaker. My problem is now: dexmakers methods operate on a higher level than those of classfilewriter. For example i can't implement add(int theOpCode), because dexmaker always expects some kind of target (e.g. a local variable). Is there a better point to plug this in? Or is it just plain stupid to try it because it won't fit? Any other comments?

**Comment by F43nd1r** [comment]
OK, so I got my own project working on android with optimization in use by provididng custom class loading. For anyone who is interested - https://github.com/F43nd1r/rhino-android. It seems to work pretty good, altough I haven't tested it a lot.

**Comment by gbrail** [comment]
Glad to hear it!

We've had a number of questions about running on Android, so if you ever
get your stuff into shape that it could be shared, you might want to
consider contributing a sample that we could put in the Rhino GitHub repo
so that others can easily find it.

On Thu, Jan 14, 2016 at 1:16 PM, F43nd1r <notifications@github.com> wrote:

> Closed #211 <https://github.com/mozilla/rhino/issues/211>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/211#event-515433917>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by F43nd1r** [comment]
I am currently working on running all the java tests on an android device. While most run fine, I don't understand some of the errors:
- OverloadTest.testJSObjectToMap throws "org.mozilla.javascript.EvaluatorException: The choice of Java method org.mozilla.javascript.tests.OverloadTest.x matching JavaScript argument types (object) is ambiguous; candidate methods are:
class java.lang.String x(java.util.Map)
class java.lang.String x(java.util.Collection)
class java.lang.String x(java.lang.Runnable)"
- ParserTest.testReportError throws "junit.framework.ComparisonFailure: expected:<"[eval]" is not a valid ide...> but was:<"[{0}]" is not a valid ide...>"
- ObjectToStringNullUndefinedTest.testToStringNullUndefined throws "org.junit.ComparisonFailure: expected:<[object [Null]]> but was:<[object [Object]]>"
- ToSourceTest.testArrowFunctionToSource throws "org.mozilla.javascript.EvaluatorException: syntax error"

**Comment by F43nd1r** [comment]
FYI [here](https://github.com/F43nd1r/rhino-android-example) is a sample application showcasing how to use rhino on android, as you asked for.

**Comment by F43nd1r** [comment]
reopen for awareness.

**Comment by krudos** [comment]
i am having problem with android kitkat and big js files around 500kb

**Comment by Betalord** [comment]
Hi,
I'd like to know what is the state of the matter currently? Has this problem been resolved? I'd need to use Rhino on Android with JavaAdapter (due to subclassing etc.), so I'm trying to figure out what my options are.

**Comment by F43nd1r** [comment]
My project is running, altough according to some bug reports, it has problems in certain situations. The solution is not optimal, because it adds another compile step (someone with enough knowledge of both jvm and art bytecode could probably cut one compile step). Feel free to try the project - https://github.com/F43nd1r/rhino-android

**Comment by AlexTrotsenko** [comment]
As I already mentioned in https://github.com/mozilla/rhino/issues/282, [Byte Buddy](http://bytebuddy.net/) supports both Java and Android byte code generation - thus it could be a good option for `Rhino` as well.

**Comment by hypersoft** [comment]
@F43nd1r , I managed to in-build your project with a custom rhino, that not only does the runtime compile classloading, it also changed the classloader profile to aggressive. Normally, if you request a package from the Mozilla Packages object, it caches the request, if the first request is a 404, adding to the classpath won't help. I built a URL classloader and injected it into the Context class as the default class loader (single-instance). It keeps track of all package requests, so i can know what packages and classes have been loaded by the script runtime, maybe even put a security wrapper in there.

Your method works fine with that, as far as I know. Good work by the way. I've managed to cut all the dalvik code, plus your project down to 24KB.

https://github.com/hypersoft/NanoStarbox

**Comment by hypersoft** [comment]
@Mozilla, seems you could make it easy for android users to use your code, if you put the instrumentation to use his classloader, when available. Then an archive such as the nano-archive [i have built](https://github.com/hypersoft/NanoStarbox/blob/NSR8/module/support/archive/builtins/nano-android-jit.jar), could automagically load for the android users with the simple addition of some class files to their own classpath.

**Comment by hypersoft** [comment]
@F43nd1r , one more thing, that [nano archive](https://github.com/hypersoft/NanoStarbox/blob/NSR8/module/support/archive/builtins/nano-android-jit.jar), basically traces the Dalvik API route of your project. you can use that route, plus the sources to construct your own android debugging layer... The route in place is factory code.

**Comment by hypersoft** [comment]
This is also very useful information for anyone [Implementing an ART Just-In-Time (JIT) Compiler](https://source.android.com/devices/tech/dalvik/jit-compiler), such as Faendir's project. It details how to configure the platform for debugging and other tricks of the trade.
