### ISSUE TITLE
Rhino 1.7.7 test suite failure, e.g. StackOverflowError

### ISSUE THREAD

**Issue by hartwork** [mozilla/rhino#225]
Increasing the test suite RAM limit did not not help.
Java is Oracle Java 1.8.0.51.

Is failure to be expected?

```
# fgrep '[junit]' /some/path.log | fgrep -C 5 'output from'
    [junit] 437988.jstest: passed
    [junit] 420012.jstest: passed
    [junit] 401561.jstest: passed
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.313 sec
    [junit] Running org.mozilla.javascript.tests.MozillaSuiteTest
    [junit] output from test live/Methods/println-001.js
    [junit] java.lang.StackOverflowError
    [junit]     at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2269)
    [junit]     at org.mozilla.javascript.ScriptRuntime.topScopeName(ScriptRuntime.java:1947)
    [junit]     at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1849)
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_4277._c_objRecurse_1(Unknown Source)
--
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_4277._c_objRecurse_1(Unknown Source)
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_4277.call(Unknown Source)
    [junit]     at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:359)
    [junit]     at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2505)
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_4277._c_objRecurse_1(Unknown Source)
    [junit] output from test live/Methods/println-001.js
    [junit] java.lang.StackOverflowError
    [junit]     at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:468)
    [junit]     at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:334)
    [junit]     at org.mozilla.javascript.ImporterTopLevel.get(ImporterTopLevel.java:96)
    [junit]     at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2269)
--
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_6860._n1(Unknown Source)
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_6860._c_objRecurse_1(Unknown Source)
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_6860._n1(Unknown Source)
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_6860._c_objRecurse_1(Unknown Source)
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_6860._n1(Unknown Source)
    [junit] output from test live/Methods/println-001.js
    [junit] Tests run: 7251, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 355.544 sec
    [junit] Running org.mozilla.javascript.tests.NativeArrayTest
    [junit] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec
    [junit] Running org.mozilla.javascript.tests.NativeStringTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
--
    [junit] 437988.jstest: passed
    [junit] 420012.jstest: passed
    [junit] 401561.jstest: passed
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.158 sec
    [junit] Running org.mozilla.javascript.tests.MozillaSuiteTest
    [junit] output from test live/Methods/println-001.js
    [junit] java.lang.StackOverflowError
    [junit]     at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:468)
    [junit]     at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:334)
    [junit]     at org.mozilla.javascript.ImporterTopLevel.get(ImporterTopLevel.java:96)
    [junit]     at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2269)
--
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_4277._c_objRecurse_1(Unknown Source)
    [junit]     at org.mozilla.javascript.gen._some_path_Rhino1_7_7_RELEASE_testsrc_tests_js1_5_Regress_regress_96128_n_js_4277.call(Unknown Source)
    [junit] In "/var/tmp/portage/dev-java/rhino-1.7.7/work/rhino-Rhino1_7_7_RELEASE/testsrc/tests/js1_5/String/regress-56940-01.js":
    [junit]  FAILED! BigO 2 < 2 : Expected value 'true', Actual value 'false' 
    [junit] 
    [junit] output from test live/Methods/println-001.js
    [junit] java.lang.StackOverflowError
    [junit]     at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:468)
    [junit]     at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:334)
    [junit]     at org.mozilla.javascript.ImporterTopLevel.get(ImporterTopLevel.java:96)
    [junit]     at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2269)
--
    [junit]     at org.mozilla.javascript.optimizer.Optimizer.rewriteForNumberVariables(Optimizer.java:252)
    [junit]     at org.mozilla.javascript.optimizer.Optimizer.rewriteForNumberVariables(Optimizer.java:252)
    [junit]     at org.mozilla.javascript.optimizer.Optimizer.rewriteForNumberVariables(Optimizer.java:252)
    [junit]     at org.mozilla.javascript.optimizer.Optimizer.rewriteForNumberVariables(Optimizer.java:252)
    [junit]     at org.mozilla.javascript.optimizer.Optimizer.rewriteForNumberVariables(Optimizer.java:252)
    [junit] output from test live/Methods/println-001.js
    [junit] Tests run: 7251, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 358.143 sec
    [junit] TEST org.mozilla.javascript.tests.MozillaSuiteTest FAILED
    [junit] Running org.mozilla.javascript.tests.NativeArrayTest
    [junit] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
    [junit] Running org.mozilla.javascript.tests.NativeStringTest
```

**Comment by eshepelyuk** [comment]
There is armleast one test case that intentionally runs JS script that results in `StackOverflowError`.
So you would see this expection in logs even if all tests passed OK.

**Comment by hartwork** [comment]
Good to know. It reads
```
    [junit] Tests FAILED
```
at the end, though.

**Comment by eshepelyuk** [comment]
Yes, because there are other failures,accoridng to logs you've attached. E.g.
```
FAILED! BigO 2 < 2 : Expected value 'true', Actual value 'false
```
Similar messages appears from couple of *unstable* tests that randomly fail on some computers.

**Comment by hartwork** [comment]
I see. Would it be possible to separate the stable from the unstable ones?

**Comment by gbrail** [comment]
I have disabled a few of the "unstable" tests. They appear to be very old tests that are looking for performance regressions in interpreted mode, and for some reason they fail most often on Java 8 (?!?)

Anyway, I'll keep this open and try to disable more of these.

**Comment by gbrail** [comment]
Build is pretty stable now.
