### ISSUE TITLE
java.lang.NoClassDefFoundError: org.mozilla.javascript.Kit

### ISSUE THREAD

**Issue by cakedevp** [mozilla/rhino#264]
I started getting this error on my Android 4.4.2 tablet but when I run my application on my Nexus 6 Android 6.0.1 everything works normally:

```java
FATAL EXCEPTION: main
Process: com.expertfect.multistop2, PID: 9133
java.lang.NoClassDefFoundError: org.mozilla.javascript.Kit
    at org.mozilla.javascript.ScriptRuntime.<clinit>(ScriptRuntime.java:112)
    at org.mozilla.javascript.Context.<clinit>(Context.java:301)
    at com.expertfect.multistop2.scripting.AppScript.<init>(AppScript.java:49)
    at com.expertfect.multistop2.activities.EventsActivity.onCreate(EventsActivity.java:132)
    at android.app.Activity.performCreate(Activity.java:5264)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
    at android.app.ActivityThread.access$800(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5292)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
    at dalvik.system.NativeStart.main(Native Method)
```

The error comes from this line `org.mozilla.javascript.Context.enter();` and is being called from an Activity's onCreate method.

I'm using Android Studio with these settings for the app project:
- compileSdkVersion 23
- minSdkVersion 15
- targetSdkVersion 22

The version of Rhino I'm using is 1.7.7.1 and I tried downgrading to 1.7.7, 1.7.6, 1.7R5 but I still keep getting the same error in the same line.

I would really appreciate any help on this.

Thanks in advance.

**Comment by cakedevp** [comment]
I just solved the issue. Apparently it was a problem with the gradle version. I updated my gradle version to 2.10 and the exception isn't showing any more.

Thanks.
