### ISSUE TITLE
Do we support XMLHttpRequest?

### ISSUE THREAD

**Issue by mawenpeng** [mozilla/rhino#287]
Sometimes I port/run JS from some web pages, there are XMLHttpRequest objects in them.
This throws errors.

Thanks.

**Comment by mawenpeng** [comment]
In web3.txt(js), line 4231 will show errors like this.

Exception in thread "main" org.mozilla.javascript.EcmaError: TypeError: [object Object] is not a function, it is object. (web3.js#4231)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3981)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4036)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4024)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2502)
	at org.mozilla.javascript.gen.web3_js_1._c_anonymous_305(web3.js:4231)
	at org.mozilla.javascript.gen.web3_js_1.call(web3.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.web3_js_1._c_anonymous_306(web3.js:4245)
	at org.mozilla.javascript.gen.web3_js_1.call(web3.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.web3_js_1._c_anonymous_425(web3.js:6026)
	at org.mozilla.javascript.gen.web3_js_1.call(web3.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.web3_js_1._c_anonymous_361(web3.js:4989)
	at org.mozilla.javascript.gen.web3_js_1.call(web3.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen._cmd__7._c_script_0(<cmd>:1)
	at org.mozilla.javascript.gen._cmd__7.call(<cmd>)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
	at org.mozilla.javascript.gen._cmd__7.call(<cmd>)
	at org.mozilla.javascript.gen._cmd__7.exec(<cmd>)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1219)
	at org.moon.wema.Test2.main(Test2.java:51)


[web3.txt](https://github.com/mozilla/rhino/files/550393/web3.txt)

**Comment by gbrail** [comment]
No, that's not one of the things that's built in to Rhino (in fact, there is no network I/O or HTTP built in to Rhino at all). Developers who want to embed Rhino into platforms where this sort of thing is a requirement usually build the code in Java and use one of the various patterns that let you call the Java code from JavaScript.

**Comment by mawenpeng** [comment]
Thanks.
