### ISSUE TITLE
Not able to execute any PAC functions like dnsDomainIs()

### ISSUE THREAD

**Issue by anilwo** [mozilla/rhino#306]
throws below errors:
org.mozilla.javascript.EcmaError: ReferenceError: "dnsDomainIs" is not defined.
(sample_pac.js#4)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.jav
a:3689)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.jav
a:3667)
        at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java
:3752)
        at org.mozilla.javascript.ScriptRuntime.getNameFunctionAndThis(ScriptRun
time.java:2175)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:
61)
        at org.mozilla.javascript.gen.sample_pac_js_1._c_FindProxyForURL_1(sampl
e_pac.js:4)
        at org.mozilla.javascript.gen.sample_pac_js_1.call(sample_pac.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:
63)
        at org.mozilla.javascript.gen.sample_pac_js_1._c_script_0(sample_pac.js:
32)
        at org.mozilla.javascript.gen.sample_pac_js_1.call(sample_pac.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:3
94)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:309
0)
        at org.mozilla.javascript.gen.sample_pac_js_1.call(sample_pac.js)
        at org.mozilla.javascript.gen.sample_pac_js_1.exec(sample_pac.js)
        at org.mozilla.javascript.Context.evaluateReader(Context.java:1110)
        at RunScript.main(RunScript.java:44)

**Comment by gbrail** [comment]
Rhino is a pretty generic JavaScript engine that can do a lot of things.
I'm not aware of a built-in function called "dnsDomainIs" so I'm not sure
what the problem is here.

Is it possible that the problem is in some other component that uses Rhino?
