### ISSUE TITLE
TypeError: Cannot find function split in object

### ISSUE THREAD

**Issue by deepakmalode** [mozilla/rhino#345]
following js code is throwing exception saying "TypeError: Cannot find function split in object". 

var a = "test";
var b = "case";

var c = a + ':' + b;

var d = c.split(':');

Following is the complete stack trace

Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot find function split in object test:case. (<Unknown source>#6)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4142)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4120)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4153)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4172)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4244)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2533)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2515)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1322)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3452)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1275)

**Comment by gbrail** [comment]
This works for me. What version of Rhino are you running? I don't recall how long "split" has been in the code base.

**Comment by deepakmalode** [comment]
its failing when all the variables are global scope. 

 we are using 1.7.7.2

**Comment by sainaen** [comment]
I can't reproduce it either.

@deepakmalode Could you please share the code where you're setting up Rhino? Does this also happen if you run your code from Rhino's Shell (something like `java -jar rhino-1.7.7.2.jar -opt -1 -f source.js`)?

What is printed out if you add
```js
print(c.toSource());
print(String.prototype.split.toSource());
```
before `var d = c.split(':');`? (In case `print()` is missing in your scope, try `Packages.java.lang.System.out.println()` instead.)

**Comment by deepakmalode** [comment]
you are right.  The error was due to we using  rhino through ScriptEngine  through com.sun.phobos:com.sun.phobos  package. This issue does not occur when we use rhino directly.  Guess something in there is introducing the problem . 
As this is not related to rhino directly, you can close the issue. 

Thanks for the active response and support !!!

**Comment by gbrail** [comment]
Glad to hear that it's working better for you!
