### ISSUE TITLE
getOwnPropertyDescriptor of Java wrapped objects getter/setter functions can not be invoked using "call"/"apply"

### ISSUE THREAD

**Issue by tmallery** [mozilla/rhino#348]
I'm getting an error when I try to "call" the get/set properties of the result of Object.getOwnPropertyDescriptor() when a wrapped Java object is the target.

org.mozilla.v17.javascript.EvaluatorException: Can't find method org.mozilla.v17.javascript.Callable.call(object,string). (exp#69)
	at org.mozilla.v17.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.v17.javascript.Context.reportRuntimeError(Context.java:971)
	at org.mozilla.v17.javascript.Context.reportRuntimeError(Context.java:1026)
	at org.mozilla.v17.javascript.Context.reportRuntimeError1(Context.java:989)
	at org.mozilla.v17.javascript.NativeJavaMethod.call(NativeJavaMethod.java:145)

In Chromes JS engine, the getter/setter properties of the object returned from Object.getOwnPropertyDescriptor() are functions which can then be executed using "call" and "apply". This is not true for Rhino because the get and set functions are MemberBox objects and not FunctionObjects.

**Comment by p-bakker** [comment]
@tmallery am closing this as I assume https://github.com/mozilla/rhino/pull/353 fixed it. If not, please reopen
