### ISSUE TITLE
java.util.MissingResourceException: Can't find bundle for base name org.mozilla.javascript.resources.Messages

### ISSUE THREAD

**Issue by CaledoniaProject** [mozilla/rhino#382]
I'm using Rhino in OpenRASP project, and recently I've updated JDK to 

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

Now rhino won't initialize, 

```
java.util.MissingResourceException: Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale en_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at org.mozilla.javascript.ScriptRuntime$DefaultMessageProvider.getMessage(ScriptRuntime.java:4096)
	at org.mozilla.javascript.ScriptRuntime.getMessage(ScriptRuntime.java:4080)
	at org.mozilla.javascript.ScriptRuntime.getMessage1(ScriptRuntime.java:4034)
	at org.mozilla.javascript.Parser.lookupMessage(Parser.java:298)
	at org.mozilla.javascript.Parser.addWarning(Parser.java:269)
	at org.mozilla.javascript.Parser.addStrictWarning(Parser.java:262)
	at org.mozilla.javascript.Parser.warnMissingSemi(Parser.java:3797)
```

What should I do now?

**Comment by gbrail** [comment]
The only message bundles in the Rhino distro are the default (English) and
French. I'm not sure why the code isn't falling back to the default bundle
in that case but I'm rusty on the gory details of the Java
internationalization stuff.

Do you have your locale settings set up in some unusual way?

Also, what release of Rhino are you using and how are you invoking it?

**Comment by CaledoniaProject** [comment]
Hmm, on MacOS, downgrading to JDK "1.8.0_144" worked for me.

**Comment by gbrail** [comment]
Rhino builds and tests fine on a Mac with 1.8.0_161. It's hard to tell from
your project how to build it and reproduce the problem -- perhaps if
there's a test that we can run on your repo it'll be easier to figure out.

**Comment by CaledoniaProject** [comment]
Yeah, just figured out that as well ... rhino works well without -javaagent and java's retransform mechanism.

Let's close this issue, thanks for the assist :-)
