### ISSUE TITLE
FAILED ASSERTION due to malformed destructuring syntax

### ISSUE THREAD

**Issue by rohanpadhye** [mozilla/rhino#405]
Rhino 1.7.8:
```
[x (y)] = 2, 3
```
Expected: syntax error (`EvaluatorException`)

Instead, I get:
```
java.lang.IllegalStateException: FAILED ASSERTION: unexpected token: CALL
	at org.mozilla.javascript.Kit.codeBug(Kit.java:433)
	at org.mozilla.javascript.IRFactory.decompile(IRFactory.java:2407)
	at org.mozilla.javascript.IRFactory.decompileArrayLiteral(IRFactory.java:2419)
	at org.mozilla.javascript.IRFactory.decompile(IRFactory.java:2381)
	at org.mozilla.javascript.IRFactory.transformAssignment(IRFactory.java:426)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:212)
	at org.mozilla.javascript.IRFactory.transformExprStmt(IRFactory.java:516)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:209)
	at org.mozilla.javascript.IRFactory.transformScript(IRFactory.java:1042)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:192)
	at org.mozilla.javascript.IRFactory.transformTree(IRFactory.java:117)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2540)
	at org.mozilla.javascript.Context.compileString(Context.java:1507)
	at org.mozilla.javascript.Context.compileString(Context.java:1496)
```

Found using [JQF](https://github.com/rohanpadhye/jqf).

**Comment by rohanpadhye** [comment]
Hi, it's been more than one year since this was first reported. Can someone please confirm the bug?

**Comment by p-bakker** [comment]
Such code should throw a SyntaxError (nowadays)

**Comment by tuchida** [comment]
ref. #1519, #1520
Applying these will correct the problem.
```
$ ./gradlew run -q --console=plain --args="-version 200"
Rhino 1.7.16-SNAPSHOT
js> [x (y)] = 2, 3
js: line 2: Invalid assignment left-hand side.
js: 
js: ^
js: line 2: Compilation produced 1 syntax errors.
```
