### ISSUE TITLE
NullPointerException in BodyCodeGen

### ISSUE THREAD

**Issue by rohanpadhye** [mozilla/rhino#410]
Input to Rhino 1.7.8:
```
[a.b.c] = x
```

Throws:
```
java.lang.NullPointerException
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2178)
	at org.mozilla.javascript.optimizer.BodyCodegen.visitGetProp(Codegen.java:5088)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2548)
	at org.mozilla.javascript.optimizer.BodyCodegen.visitSetProp(Codegen.java:5132)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2610)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2309)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2807)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2309)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2807)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:2059)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1870)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(Codegen.java:1292)
	at org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:307)
	at org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:166)
	at org.mozilla.javascript.optimizer.Codegen.compile(Codegen.java:75)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2551)
	at org.mozilla.javascript.Context.compileString(Context.java:1507)
	at org.mozilla.javascript.Context.compileString(Context.java:1496)
```

Found using [JQF](https://github.com/rohanpadhye/jqf); auto-generated test case was `[Vinu.en.en]=proted`.

**Comment by rohanpadhye** [comment]
Hi, it's been more than one year since this was first reported. Can someone please confirm the bug?

**Comment by p-bakker** [comment]
While the stacktrace above was taken when running in non-interpreted mode, a similar issue occurs in interpreted mode
