### ISSUE TITLE
ExceptionInInitializerError after applied proguard in Android

### ISSUE THREAD

**Issue by macroday** [mozilla/rhino#412]
Hi, Please check the below error and tell me the solution for this.

java.lang.ExceptionInInitializerError
       at org.a.b.l.a(Context.java:396)
       at org.a.b.l.b(Context.java:3391)
       at com.xx.yy.view.Activity.g(MyActivity.java:16)
       at com.xx.yy.view.Activity.onActivityResult(MyActivity.java:235)
       at android.app.Activity.dispatchActivityResult(Activity.java:6931)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4090)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4137)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by gbrail** [comment]
We're going to need some more information to figure that out. For instance,
there is no Rhino code in that stack trace. There is a class called
"Context" but it only has 2789 lines...

**Comment by macroday** [comment]
I could provide a min of code instead of all. Pls check below.

This is my code,
```
org.mozilla.javascript.Context jsContext = org.mozilla.javascript.Context.enter();
jsContext.setOptimizationLevel(-1);
scope = jsContext.initSafeStandardObjects();
jsContext.evaluateString(scope, jsScript, "WeighBag", 1, null);
```
And i have referred at Android docs that mentioned of ExceptionInInitializerError occur at static initializer state,

> Signals that an unexpected exception has occurred in a static initializer. An ExceptionInInitializerError is thrown to indicate that an exception occurred during evaluation of a static initializer or the initializer for a static variable.
> 
> As of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The "saved throwable object" that may be provided at construction time and accessed via the getException() method is now known as the cause, and may be accessed via the getCause() method, as well as the aforementioned "legacy method."

As i can see you have used static method to initialize the context. Pls refer below,

```
 public static Context enter() {
        return enter((Context)null);
    }
```

I thought it raised might be of this. Pls help me to fix it.

**Comment by macroday** [comment]
@sainaen 

I have attached my proguard rules at below. 

```
-dontoptimize
-keeppackagenames org.mozilla.**
-keep class org.mozilla.** { *; }
-dontwarn org.mozilla.**
-dontwarn com.squareup.**
-dontwarn org.xmlpull.v1.**
-dontnote org.xmlpull.v1.**
-keep class org.xmlpull.** { *; }
-keep class com.google.android.gms.internal.** { *; }
-keepattributes Signature,SourceFile,LineNumberTable
-assumenosideeffects class android.util.Log {
    *;
}
```

This error occur when i comment the below statements in proguard rules,

```
-dontoptimize
-keeppackagenames org.mozilla.**
-keep class org.mozilla.** { *; }
-dontwarn org.mozilla.**
```

 I think the cause of error due to use the **Context** with package because while optimizing the app android will change the all package name. Please give me a better solution to fix it soon.
