### ISSUE TITLE
NoSuchMethodException with JavaAdapter

### ISSUE THREAD

**Issue by Perkovec** [mozilla/rhino#424]
I use OkHTTP3 library for make asynchronous https request in android via Rhino, but has NoSuchMethodException.

Code:
```javascript
var response = this.httpClient.newCall(request).enqueue(new JavaAdapter(Packages.okhttp3.Callback, {
onFailure: function onFailure(call, e) {
    Packages.android.widget.Toast.makeText(scope.context, e.getMessage(), Packages.android.widget.Toast.LENGTH_LONG).show();
},
onResponse: function onResponse(call, response) {
    try {
        var responseBody = response.body();
        if (onSuccess)
            onSuccess(responseBody.string());
    } catch(e){
        Packages.android.widget.Toast.makeText(scope.context, e.message, Packages.android.widget.Toast.LENGTH_LONG).show();
    }
}
}));
```

**Comment by gbrail** [comment]
It's hard to tell what the problem might be. Do you have any more details,
like a stack trace?

**Comment by Perkovec** [comment]
@gbrail

```
04-21 09:19:11.096 32150 32150 W   dalvikvm com.test.testuiservice           VFY: unable to resolve virtual method 1160: Ljava/lang/reflect/Method;.isDefault ()Z
04-21 09:19:11.456 32150 32150 W   dalvikvm com.test.testuiservice           threadid=1: thread exiting with uncaught exception (group=0x416d6e18)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     FATAL EXCEPTION: main
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     Process: com.test.testuiservice, PID: 32150
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     java.lang.NoSuchMethodError: java.lang.reflect.Method.isDefault
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.jdk18.VMBridge_jdk18.isDefaultMethod(VMBridge_jdk18.java:19)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.JavaAdapter.createAdapterCode(JavaAdapter.java:388)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.JavaAdapter.getAdapterClass(JavaAdapter.java:330)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:173)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:86)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:364)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1617)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:911)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at org.mozilla.javascript.Context.evaluateString(Context.java:1262)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at com.test.testuiservice.MainService.onStartCommand(MainService.java:69)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3187)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at android.app.ActivityThread.access$2100(ActivityThread.java:156)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at android.os.Handler.dispatchMessage(Handler.java:102)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at android.os.Looper.loop(Looper.java:157)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at android.app.ActivityThread.main(ActivityThread.java:5872)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at java.lang.reflect.Method.invokeNative(Native Method)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at java.lang.reflect.Method.invoke(Method.java:515)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
04-21 09:19:11.466 32150 32150 E   AndroidRuntime com.test.testuiservice     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by gbrail** [comment]
The current version of Rhino only runs on Java 8 and up. Is it possible
that the Android release you're running on doesn't have the features of
Java 8?

Has anyone else who runs on Android had success with the latest release?

**Comment by p-bakker** [comment]
Closing this case as it's missing the info to proceed.

Looks like the version of Java/dalvikvm you're running on isn't (100%) compatible with Java 8
