### ISSUE TITLE
Unable to use jspdf.js in rhino (missing name after . operator exception) 

### ISSUE THREAD

**Issue by ShrutikaUkey** [mozilla/rhino#430]
Rhino throws  missing name after . operator exception for  below source code 
 if (typeof gen.return !== "function") {
      this.return = undefined;
    }
 AsyncGenerator.prototype.return = function (arg) {
    return this._invoke("return", arg);
  };

Caused by: sun.org.mozilla.javascript.internal.EvaluatorException: missing name after . operator (<Unknown source>#95)
	at sun.org.mozilla.javascript.internal.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:109)
	at sun.org.mozilla.javascript.internal.DefaultErrorReporter.error(DefaultErrorReporter.java:96)
	at sun.org.mozilla.javascript.internal.Parser.addError(Parser.java:231)
	at sun.org.mozilla.javascript.internal.Parser.addError(Parser.java:209)
	at sun.org.mozilla.javascript.internal.Parser.reportError(Parser.java:266)
	at sun.org.mozilla.javascript.internal.Parser.reportError(Parser.java:253)
	at sun.org.mozilla.javascript.internal.Parser.reportError(Parser.java:246)
	at sun.org.mozilla.javascript.internal.Parser.propertyAccess(Parser.java:2644)
	at sun.org.mozilla.javascript.internal.Parser.memberExprTail(Parser.java:2520)
	at sun.org.mozilla.javascript.internal.Parser.memberExpr(Parser.java:2495)
	at sun.org.mozilla.javascript.internal.Parser.unaryExpr(Parser.java:2369)
	at sun.org.mozilla.javascript.internal.Parser.mulExpr(Parser.java:2292)
	at sun.org.mozilla.javascript.internal.Parser.addExpr(Parser.java:2274)
	at sun.org.mozilla.javascript.internal.Parser.shiftExpr(Parser.java:2253)
	at sun.org.mozilla.javascript.internal.Parser.relExpr(Parser.java:2226)
	at sun.org.mozilla.javascript.internal.Parser.eqExpr(Parser.java:2196)
	at sun.org.mozilla.javascript.internal.Parser.bitAndExpr(Parser.java:2183)
	at sun.org.mozilla.javascript.internal.Parser.bitXorExpr(Parser.java:2170)
	at sun.org.mozilla.javascript.internal.Parser.bitOrExpr(Parser.java:2157)
	at sun.org.mozilla.javascript.internal.Parser.andExpr(Parser.java:2144)
	at sun.org.mozilla.javascript.internal.Parser.orExpr(Parser.java:2131)
	at sun.org.mozilla.javascript.internal.Parser.condExpr(Parser.java:2107)
	at sun.org.mozilla.javascript.internal.Parser.assignExpr(Parser.java:2076)
	at sun.org.mozilla.javascript.internal.Parser.expr(Parser.java:2053)
	at sun.org.mozilla.javascript.internal.Parser.statementHelper(Parser.java:1082)
	at sun.org.mozilla.javascript.internal.Parser.statement(Parser.java:944)
	at sun.org.mozilla.javascript.internal.Parser.statements(Parser.java:899)
	at sun.org.mozilla.javascript.internal.Parser.block(Parser.java:1734)
	at sun.org.mozilla.javascript.internal.Parser.statementHelper(Parser.java:1053)
	at sun.org.mozilla.javascript.internal.Parser.statement(Parser.java:944)
	at sun.org.mozilla.javascript.internal.Parser.ifStatement(Parser.java:1125)
	at sun.org.mozilla.javascript.internal.Parser.statementHelper(Parser.java:990)
	at sun.org.mozilla.javascript.internal.Parser.statement(Parser.java:944)
	at sun.org.mozilla.javascript.internal.Parser.parseFunctionBody(Parser.java:653)
	at sun.org.mozilla.javascript.internal.Parser.function(Parser.java:838)
	at sun.org.mozilla.javascript.internal.Parser.parseFunctionBody(Parser.java:650)
	at sun.org.mozilla.javascript.internal.Parser.function(Parser.java:838)
	at sun.org.mozilla.javascript.internal.Parser.primaryExpr(Parser.java:2798)

**Comment by Jugolo** [comment]
Return is a Keyword and There need to be a identify after .

**Comment by Krinkle** [comment]
Return is keyword, but as of ES5, keywords are not disallowed in property names and identifier names.

Per <https://es5.github.io/#A.3> and <https://es5.github.io/#x7.6>, keywords are reserved from identifiers (e.g. start of an expression), but very specifically not reserved from identifier names (e.g. object keys, property names, member expressions).

For example, ES6 Promise, has methods `catch` and `finally`, which work fine.

**Comment by p-bakker** [comment]
Tested this with the following running sample code (which I think should demonstrate the issue you reported as well) on the latest master (Context.VERSION_ES6) and no error was thrown:
```
				var x = "";
				
				if (typeof x.return !== 'function') {}
```

So closing this issue. Feel free to reopen if you can still reproduce this on the latest master
