### ISSUE TITLE
Illegal Reflective Operation

### ISSUE THREAD

**Issue by ArnaudBuchholz** [mozilla/rhino#462]
I have a project based on Rhino that throws this new error:

WARNING: Illegal reflective access by org.mozilla.javascript.MemberBox (file:/E:/Nano%20et%20Nono/Arnaud/dev/GitHub/gpf-js/node_modules/rhino-1_7r5-bin/rhino1_7R5/js.jar) to method sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.mozilla.javascript.MemberBox
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Is there anything we can do to prevent that?

**Comment by gbrail** [comment]
A few people have seen this with Java 9. The fix doesn't seem simple but
perhaps someone can try...

This happens because, via reflection, Rhino is trying to call a method that
is on a class that's not supposed to be visible through the Java 9 module
system.

My theory is that some code using Rhino is trying to call
java.net.HttpURLConnection.setRequestMethod(). However since this is
implemented by the sun.net.www.protocol... class, and Rhino is calling it
via reflection, the JVM doesn't know that Rhino is trying to use the
interface, and thinks that it's illegally calling a method on a class
that's not supposed to be visible.

I can think of two ways to "fix" this...

1) In MemberBox, we can add some code that walks the class tree upwards via
reflection to try and discover the highest-level interface that implements
a method, and try to call that method rather than the method on the
implementing class. I don't know exactly how to do this but it seems
plausible.

2) We can change Rhino's bytecode generation to directly insert calls to
Java methods into the generated bytecode rather than using reflection via
MemberBox. This would be a lot harder and not help us when in interpreted
mode. I'm pretty sure that this is what Nashorn did.

2 and a half) perhaps this works differently when InvokeDynamic and its
MethodHandles are used...

If anyone has time, it'd be great to write a little bit of experimental
code to test this hypothesis and possible solutions!

**Comment by ArnaudBuchholz** [comment]
First of all, thank you for taking the time to answer.

I am clearly not a JAVA guy but I understand the reflection concept.

_"This happens because, via reflection, Rhino is trying to call a method that
is on a class that's not supposed to be visible through the Java 9 module
system."_

I am not sure what this Java 9 module system is but if the method is available on the class (provided it is public) I don't see why we wouldn't be able to invoke it.

The code generating the warning is:

```javascript
    var httpConnection = new java.net.URL(request.url).openConnection();
    httpConnection.setRequestMethod(request.method);
```

And, funny enough, the exact same code works fine on Nashorn...

**Comment by ArnaudBuchholz** [comment]
After checking the documentation, I start to better understand the issue:

[openConnection](https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openConnection()) returns an [URLConnection](https://docs.oracle.com/javase/7/docs/api/java/net/URLConnection.html) object that doesn't have the setRequestMethod method.

Hence I need to typecast the result into an [HttpURLConnection](https://docs.oracle.com/javase/7/docs/api/java/net/HttpURLConnection.html).

Any clue on typecasting in Rhino?

**Comment by Moisan** [comment]
My understanding is that this is currently blocking the use of Rhino with Java 16 due to [JEPS 396](https://openjdk.java.net/jeps/396).

**Comment by jcompagner** [comment]
i am currently looking into this
so this is not fixed yet in NativeJavaObject/MemberBox in the current source?

(i checked the latest release and its still a problem)

```
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalAccessException: class org.mozilla.javascript.MemberBox cannot access class sun.nio.ch.FileChannelImpl (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @7d37608b
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:146)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:45)
        at org.mozilla.javascript.gen._stdin__7._c_script_0(Unknown Source)
        at org.mozilla.javascript.gen._stdin__7.call(Unknown Source)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.gen._stdin__7.call(Unknown Source)
        at org.mozilla.javascript.gen._stdin__7.exec(Unknown Source)
        at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:497)
        at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:181)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:101)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:163)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:138)
Caused by: java.lang.IllegalAccessException: class org.mozilla.javascript.MemberBox cannot access class sun.nio.ch.FileChannelImpl (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @7d37608b
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:687)
        at java.base/java.lang.reflect.Method.invoke(Method.java:559)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
```


this is what we now get in Rhino when running:

```
        var file = "d:/temp/rmitnl.jar";
	var is = new java.io.FileInputStream(file);
	var inputChannel = java.nio.channels.Channels.newChannel(is);
	var buffer = java.nio.ByteBuffer.allocateDirect(16 * 1024);
	application.output(inputChannel.read(buffer));
	is.close();
	inputChannel.close();
```

i will have a look if i can get the MemberBox/NativeJavaObject a bit smarter in this regard, so it wil try to just use the public interface methods instead of the actual class methods.

**Comment by jcompagner** [comment]
i was able to find a fix in MemberBox.invoke:

instead of just doing:

```
    try {
     return method.invoke(target, args);
    } catch (IllegalAccessException ex) {
```

i do:

```
            try {
				if (!method.canAccess(target)) {
					Class<?> declaredClz = method.getDeclaringClass();
					Method met = null;
					do {
						for (Class<?> interfaceClass : declaredClz.getInterfaces()) {
							try {
								met = interfaceClass.getMethod(getName(), method.getParameterTypes());
								if (met.canAccess(target))
									break;
								met = null;
							} catch (Exception e) {
							}
						}
						declaredClz = declaredClz.getSuperclass();
					} while (met == null && declaredClz != null);
					if (met != null) {
						memberObject = met;
						method = met;
					}
				}
                return method.invoke(target, args);
            } catch (IllegalAccessException ex) {
```

This does need java 9 api (canAccess(object))

so at the moment of the invoke, we check if the method is accessible.
if not then then try to find that method over all the interfaces that that declared class has or one of its superclasses.
(maybe the code should also just check the super class itself)

Check if there is a method to be found that is accessible
If that is the case then use that from now on (so it auto corrects the MemberBox itself, i think that should be fine, so that it doesn't need todo this all the time)

**Comment by jcompagner** [comment]
i pushed a change in our fork: 

https://github.com/Servoy/servoy-js-engine/commit/d68464c1bdcf14fe7894354e341aaabad120899f

that also still works for java 8 (because it uses reflection)
and also test if the super class has something

So the flow is, test if the current method is accessible, if not check the current class its interfaces if they have the same signature method that is acessible, else go to the super class and check the super class or the superclass interfaces.
If one is found, update the MemberBox to use that one from that time on.

**Comment by gbrail** [comment]
That looks a reasonable change to me, and the sort of thing that we need to do in order to address this problem. What would you think of turning it into an actual PR for Rhino?

Rhino has historically used the "org.mozilla.javascript.VMBridge" class and its friends to encapsulate this kind of version-specific code. We could create a "VMBridge_jdk9" for this purpose using that specific pattern.

The other thing I wonder is whether you can move this lookup logic so that it happens when the member is invoked rather than on each invocation -- that's going to add a ton of reflection stuff to every invocation of a native method otherwise.

**Comment by jcompagner** [comment]
The thing is how long wants rhino to be compatible on Java8?
Java 11 is already for quite some time LTS and the next LTS (java 17) is around the corner...

Its really annoying that they made Method.canAccess(Object) and not Method.canAccess(Class)
its even more annoying if you look at the implementation of that canAccess
the only thing they do is : obj.getClass()

so they use only the class!!

Why that is very annoying for Rhino is that the reflection code really works on class. we don't really have the instance there anymore
Because if it would be Method.canAccess(Class) then we could really do it once time: JavaMembers.reflect()
https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/JavaMembers.java#L466

so around that code. We could test there right away at once if we can access it..
And we call it from 2 places (and with one we don't have an instance yet the NativeJavaClass):

![image](https://user-images.githubusercontent.com/3274268/115967512-44232080-a533-11eb-9bda-990a89bc7b30.png)

So we only can do it a bit later..
we could do something like

    Object invoke(Object target, Object[] args)
    {
        Method method = method();
        try {
            try {
				if (!alreadyCheckedForAccess && !canAccess(target, method)) {
					alreadyCheckedForAccess = true;

so only do it once (and MemberBox so JavaMembers are auto corrected on the first call
I don't think it will be really suddenly different because we have different object instance (its always a one on one mapping on the exact class for us in rhino)


By the way its not that the actual invoke call has a lot of overhead: (thats more the actual reflection looking up the Methods)

	public static void main(String[] args) throws NoSuchMethodException, SecurityException, IllegalAccessException,
			IllegalArgumentException, InvocationTargetException {
		Method canAccess = Method.class.getMethod("canAccess", Object.class);
		Method toLowerCase = String.class.getMethod("toLowerCase", null);
		long time = System.currentTimeMillis();
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < 100000; i++) {
			String str = "STR" + i;
			if (toLowerCase.canAccess(str)) {
				String lwr = (String) toLowerCase.invoke(str, null);
				sb.append(lwr);
			}
		}
		System.err.println("time normal " + (System.currentTimeMillis() - time));
		System.err.println(sb.length());

		time = System.currentTimeMillis();
		sb = new StringBuilder();
		for (int i = 0; i < 100000; i++) {
			String str = "STR" + i;
			if (((Boolean) canAccess.invoke(toLowerCase, str)).booleanValue()) {
				String lwr = (String) toLowerCase.invoke(str, null);
				sb.append(lwr);
			}
		}
		System.err.println("time invoke " + (System.currentTimeMillis() - time));
		System.err.println(sb.length());

		time = System.currentTimeMillis();
		sb = new StringBuilder();
		for (int i = 0; i < 100000; i++) {
			String str = "STR" + i;
			if (toLowerCase.canAccess(str)) {
				String lwr = (String) toLowerCase.invoke(str, null);
				sb.append(lwr);
			}
		}
		System.err.println("time normal " + (System.currentTimeMillis() - time));
		System.err.println(sb.length());

		time = System.currentTimeMillis();
		sb = new StringBuilder();
		for (int i = 0; i < 100000; i++) {
			String str = "STR" + i;
			if (((Boolean) canAccess.invoke(toLowerCase, str)).booleanValue()) {
				String lwr = (String) toLowerCase.invoke(str, null);
				sb.append(lwr);
			}
		}
		System.err.println("time invoke " + (System.currentTimeMillis() - time));
		System.err.println(sb.length());
	}

**Comment by gbrail** [comment]
I don't have to look far at all to find stuff running in production on Java 8. I think it's going to be with us for a long time. IMO this project needs to support it for a few more years to come.

**Comment by jcompagner** [comment]
for me the question is then do you really need to support the main version to Java 8 for years to come?

Sometimes it is just time...

I would just make a release and say this is the last of Java8 (and maybe we only release security issues)
and then from that day on the minimal is Java11..

A lot of libraries are moving. (for example Eclipse as a whole, so all the stuff eclipse is build on all the plugins, are moving all to java 11) 

For us it is way more a problem that it doesn't work on java 16 then that it doesn't work on Java 8...

But anyway making a VMBridge_jdk11 just means that we need to remove the reflection code from there:

https://github.com/Servoy/servoy-js-engine/commit/d68464c1bdcf14fe7894354e341aaabad120899f#diff-77ee7aa99d847f94809e966ec30cd0ce88902d4f2be6cbdf1791b96c02350883R26

to there an impl of VMBridige 
(and then having VMBridge.canAccess() instead of the canAccess static call i do now)

Or yes somehow the build tool only builds that specific class for java 11..so you can do it without reflection.
(which is by the way annoying for developers, because where is that code then? if it belongs to the main code then all the IDE's will complain if you stick to Java 8 for that project, So then people will use Java 11 for development to get rid of that error and before you know it you use Java 11 api)

**Comment by carlosame** [comment]
I added two commits related to this issue in #1040: The test is perhaps too simple and I'm open to suggestions. The actual fix is not universal but is intended to be efficient (and not require dual compilations). It is compatible with your reflection approach @jcompagner, if you are willing to provide a PR :-)

Comments are welcome.
