### ISSUE TITLE
Can't work when set android.enableD8=true for android

### ISSUE THREAD

**Issue by Chris85bh** [mozilla/rhino#490]
Use D8 to build dex by setting android.enableD8=true for my android project, and then got below error:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.Class.newInstance()' on a null object reference
at org.mozilla.javascript.Kit.newInstanceOrNull(Kit.java:74)
at org.mozilla.javascript.Context.createInterpreter(Context.java:2568)
at org.mozilla.javascript.Context.createCompiler(Context.java:2561)
at org.mozilla.javascript.Context.compileImpl(Context.java:2514)
at org.mozilla.javascript.Context.compileString(Context.java:1476)
at org.mozilla.javascript.Context.compileString(Context.java:1465)
at org.mozilla.javascript.Context.evaluateString(Context.java:1216)

When set android.enableD8=false, it works well.

**Comment by Chris85bh** [comment]
This is not a bug of rhino, but the old version of gradle plugin. Closed.
