### ISSUE TITLE
IllegalStateException   at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3518)         at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)

### ISSUE THREAD

**Issue by qssq** [mozilla/rhino#505]
How to solve this problem? This JS method is frequently invoked by java, resulting in this erro

```
java.lang.IllegalStateException
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3518)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at cn.qssq666.robot.plugin.js.api.JSPluginInterface.onReceiveMsgIsNeedIntercept(JSPluginInterface.java:202)
        at cn.qssq666.robot.business.RobotContentProvider.doPluginLogic(RobotContentProvider.java:2498)
        at cn.qssq666.robot.business.RobotContentProvider.doMsgLogicAtThread(RobotContentProvider.java:1023)
        at cn.qssq666.robot.business.RobotContentProvider.doMsgLogic(RobotContentProvider.java:959)
        at cn.qssq666.robot.business.RobotContentProvider.insert(RobotContentProvider.java:940)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:264)
```

```
    @Override
    public boolean onReceiveMsgIsNeedIntercept(IMsgModel item, List<AtBeanModelI> list, boolean hasAite,
                                               boolean hasAiteMe) {

        Object pfunction = scope.get("onReceiveMsgIsNeedIntercept", scope);
        if (pfunction instanceof Function) {
            Function func = (Function) pfunction;
            Log.w(JSCns.LOG_TAG, "call onReceiveMsgIsNeedIntercept ");
            return (boolean) func.call(_cx, scope, scope,
                    new Object[]{item, list, hasAite, hasAiteMe});

        } else {
            Log.d(JSCns.LOG_TAG, " call onReceiveMsgIsNeedIntercept fail ,method not define " + pfunction);
            return false;
        }

    }

```

**Comment by qssq** [comment]
```
 try{
                    var json= JSON.parse(msgitem.getMessage())
                    var money=json["money"];
                    currentMsg=currentMsg+",金额是"+money;

                }catch(e){
                    currentMsg=currentMsg+",解析失败:"+e.message;
                }
```
i delete this ,normal  why?

**Comment by gbrail** [comment]
It's hard to tell from the stack trace what's going on. We could start with you telling us what version of Rhino you're using, and then perhaps someone can look at the code that generates that stack trace.

**Comment by p-bakker** [comment]
Closed due to missing input to proceed.

Feel free to reopen with more info
