### ISSUE TITLE
compileString throws error with let statement

### ISSUE THREAD

**Issue by tdhung80** [mozilla/rhino#526]
Hi,

In 1.7.9, I got an error with let statement.

```
String scripts = "let x = 5";
Context localContext = Context.enter();
localContext.compileString(scripts, "Line", 1, null);
```

Exception in thread "main" org.mozilla.javascript.EvaluatorException: missing ; before statement (Line#1)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
	at org.mozilla.javascript.Parser.addError(Parser.java:260)
	at org.mozilla.javascript.Parser.reportError(Parser.java:328)
	at org.mozilla.javascript.Parser.reportError(Parser.java:315)
	at org.mozilla.javascript.Parser.reportError(Parser.java:308)
	at org.mozilla.javascript.Parser.autoInsertSemicolon(Parser.java:1275)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1252)
	at org.mozilla.javascript.Parser.statement(Parser.java:1109)
	at org.mozilla.javascript.Parser.parse(Parser.java:648)
	at org.mozilla.javascript.Parser.parse(Parser.java:583)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2530)
	at org.mozilla.javascript.Context.compileString(Context.java:1515)
	at org.mozilla.javascript.Context.compileString(Context.java:1504)
	at app.App.main(App.java:14)

My Bests,
Hung Tran

**Comment by tdhung80** [comment]
I figured the problem out that the default language version is not ES6.
