### ISSUE TITLE
NoClassDefFoundError problem when using Rhino 1.7.11 RC2 in older Android versions

### ISSUE THREAD

**Issue by snechiporenko** [mozilla/rhino#560]
Rhino 1.7.11 stopped finding the java.lang.reflect.Executable class. I think this is due to the transition to Java 8 which is not supported in older versions of Android.

> Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/reflect/Executable;
    at org.mozilla.javascript.ScriptableObject.defineProperty(ScriptableObject.java:1785)
    at org.mozilla.javascript.NativeError.fillConstructorProperties(NativeError.java:98)
    at org.mozilla.javascript.IdScriptableObject.exportAsJSClass(IdScriptableObject.java:790)
    at org.mozilla.javascript.NativeError.init(NativeError.java:54)
    at org.mozilla.javascript.ScriptRuntime.initSafeStandardObjects(ScriptRuntime.java:178)
    at org.mozilla.javascript.ScriptRuntime.initStandardObjects(ScriptRuntime.java:281)
    at org.mozilla.javascript.Context.initStandardObjects(Context.java:1190)
    at org.mozilla.javascript.ImporterTopLevel.initStandardObjects(ImporterTopLevel.java:74)
    at org.mozilla.javascript.ImporterTopLevel.<init>(ImporterTopLevel.java:55)
    at org.mozilla.javascript.ImporterTopLevel.<init>(ImporterTopLevel.java:50)

Possible reasons:

- another VMBridge cleanup step (JDK 1.8 is the minimum at the moment)
- cleanup vm bridge; since we are at java 8 there is no need to check for iterator availability

Is it possible to leave backward compatibility?

**Comment by gbrail** [comment]
This caused problems for another project I'm aware of. In this case it wouldn't harm the functionality to go back to using only the old interfaces. 

Do you have a sense of how far back various Android projects would want this support to go?

**Comment by rbri** [comment]
Maybe we also have to make our Android support more clear in terms of clarifying the versions supported and maybe have the unit tests running on top of a propper android sdk.

**Comment by gbrail** [comment]
In order to fix the immediate problem, we rolled back the use of "Executable" in:

https://github.com/mozilla/rhino/pull/565

This is fixed in 1.7.11.

However, going forward Rhino continues to support Java 1.8 and up. We can try not to make changes that deliberately break for older releases, but neither do I have time to go back and re-create tests for older Java or Android releases.

If someone with more knowledge of Android is able to create some regression tests then that would be a very big help.
