### ISSUE TITLE
The try-catch block is unable to catch the exception?

### ISSUE THREAD

**Issue by YaoHouyou** [mozilla/rhino#570]
The try-catch block is unable to catch the error when i execute the code shows below, but throw  `ERR_REF_COUNT_LIMIT` error .
````
var func = function () {
	foo.prototype = new Array(1, 2, 3);
	function foo() {}
	var f = new foo();
	f.length = f;
	try {
		print("run to try");
		print("Using f will give an error: " + f);
		print("run to 2");
	} catch (e) {
		print("run to catch!")
	}
};
func();
````
The output is:
````
run to try
java.lang.StackOverflowError
...
````

This problem occurs in the `rhino-1.7.11.jar`.

**Comment by Implementist** [comment]
I debugged Rhino 1.7.11 with this testcase. **The main reason of the crash is recursive call of function 'toString' and 'valueOf' to property "length" of "length". For property 'length' of variable f refers to f itself 'f.length' has its property 'length'.**
The start point of the recurse in source is ScriptRuntime.java: 2950
```
    public static CharSequence add(CharSequence val1, Object val2) {
        return new ConsString(val1, toCharSequence(val2));
    }
```
**And when I simply the testcase to:**
```
var func = function () {
    var f = new Array(1, 2, 3);
    f.length = f;
}
func();
```
**another error occured with message:**
```
Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale zh_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
	at org.mozilla.javascript.ScriptRuntime$DefaultMessageProvider.getMessage(ScriptRuntime.java:4210)
	at org.mozilla.javascript.ScriptRuntime.getMessage(ScriptRuntime.java:4193)
	at org.mozilla.javascript.ScriptRuntime.getMessage0(ScriptRuntime.java:4141)
	at org.mozilla.javascript.NativeArray.setLength(NativeArray.java:793)
	at org.mozilla.javascript.NativeArray.setInstanceIdValue(NativeArray.java:132)
	at org.mozilla.javascript.IdScriptableObject.put(IdScriptableObject.java:466)
	at org.mozilla.javascript.NativeArray.put(NativeArray.java:451)
	at org.mozilla.javascript.ScriptableObject.putProperty(ScriptableObject.java:2507)
	at org.mozilla.javascript.ScriptRuntime.setObjectProp(ScriptRuntime.java:1743)
	at org.mozilla.javascript.ScriptRuntime.setObjectProp(ScriptRuntime.java:1737)
	at org.mozilla.javascript.gen.C__Users_Implementist_Desktop_a_js_1._c_anonymous_1(Unknown Source)
	at org.mozilla.javascript.gen.C__Users_Implementist_Desktop_a_js_1.call(Unknown Source)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:87)
	at org.mozilla.javascript.gen.C__Users_Implementist_Desktop_a_js_1._c_script_0(Unknown Source)
	at org.mozilla.javascript.gen.C__Users_Implementist_Desktop_a_js_1.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:409)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3566)
	at org.mozilla.javascript.gen.C__Users_Implementist_Desktop_a_js_1.call(Unknown Source)
	at org.mozilla.javascript.gen.C__Users_Implementist_Desktop_a_js_1.exec(Unknown Source)
	at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:600)
	at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:559)
	at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:530)
	at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:181)
	at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:101)
	at org.mozilla.javascript.Context.call(Context.java:552)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:519)
	at org.mozilla.javascript.tools.shell.Main.exec(Main.java:163)
	at org.mozilla.javascript.tools.shell.Main.main(Main.java:138)
```
**All in all, I think Infinitely recursively call of 'toString' to property of object should be detected or limited.**

**Comment by onkobu** [comment]
I came across this from another direction: examples of limiting problems to the purely technical aspect. The same happens when toString in Java is overriden, such that this.toString is called (or any other recursion). Other engines use the context, when the expression is evaluated, e.g. web developer views/ console.log limit to one level of nesting with an indicator towards the next level. The user needs to open the following levels. Node stalls, too with »RangeError: Maximum call stack size exceeded« – in catch-block.

I'd be perfectly fine with the error, sacrificing cycle detection efforts. What the reporter did was forcing an infinite recursion and it ought to be treated like this. Since it is Java StackOverflowError is perfectly fine, only fix necessary: invoke catch-block with it.

**Comment by p-bakker** [comment]
In GC the same code yields:
```
run to try
VM2392:11 run to catch! RangeError: Maximum call stack size exceeded
    at foo.join (<anonymous>)
    at foo.toString (<anonymous>)
    at foo.join (<anonymous>)
    at foo.toString (<anonymous>)
    at foo.join (<anonymous>)
    at foo.toString (<anonymous>)
    at foo.join (<anonymous>)
    at foo.toString (<anonymous>)
    at foo.join (<anonymous>)
    at foo.toString (<anonymous>)
```
