### ISSUE TITLE
Unable to use Error in strictmode after Object.preventExtensions(Error.prototype)

### ISSUE THREAD

**Issue by stijnkliemesch** [mozilla/rhino#591]
Executing the following code

    public static void main(String[] cmdlineArgs) {
        final Context context = ContextFactory.getGlobal().enterContext();
        try {
            final Script compiledScript = context.compileString(""
                    + "Object.preventExtensions(Error.prototype);\n"
                    + "new Error(\"okaythen\");\n",
                    "eval", 1, null
            );
            ScriptableObject global = context.initSafeStandardObjects();
            final Object obj
                    = ScriptRuntime.doTopCall(
                            (Context cx, Scriptable scope, Scriptable thisObj, Object[] args) -> compiledScript.exec(context, scope),
                            context, global, null, new Object[]{}, true);
            int i = 0;
        } finally {
            Context.exit();
        }
    }

This results in a thrown Exception

    Exception in thread "main" org.mozilla.javascript.EcmaError: TypeError: Cannot add properties to this object because extensible is false. (eval#2)
    	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4247)
    	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4225)
    	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4258)
    	at org.mozilla.javascript.ScriptRuntime.typeError0(ScriptRuntime.java:4264)
    	at org.mozilla.javascript.ScriptableObject.putImpl(ScriptableObject.java:2810)
    	at org.mozilla.javascript.ScriptableObject.put(ScriptableObject.java:521)
    	at org.mozilla.javascript.IdScriptableObject.put(IdScriptableObject.java:479)
    	at org.mozilla.javascript.ScriptableObject.putProperty(ScriptableObject.java:2507)
    	at org.mozilla.javascript.NativeError.make(NativeError.java:70)
    	at org.mozilla.javascript.NativeError.execIdCall(NativeError.java:144)
    	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:100)
    	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:366)
    	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2665)
    	at org.mozilla.javascript.gen.eval_1._c_script_0(eval:2)
    	at org.mozilla.javascript.gen.eval_1.call(eval)
    	at org.mozilla.javascript.gen.eval_1.exec(eval)

I'm not sure what the ECMA script spec prescribes as the expected outcome for this situation, but browsers seem to not have any such problems.

**Comment by p-bakker** [comment]
Ran your sample code against the latest master, not getting an exception anymore, so this seems to have been resolved in the meantime.

Please reopen if you can still reproduce on the latest master
