### ISSUE TITLE
Out of Memory in Rhino 1.7.7.2 parsing

### ISSUE THREAD

**Issue by vrthra** [mozilla/rhino#646]
When evaluating the following fragment, a OutofMemoryError is thrown.
```javascript
var {baz: baz => {}} = ({ [ super
] :
super
} ,
...
++ function (
) { }
) => {};
```
The exception is below:
```
$ java -jar lang/js/compilers/rhino-1.7.7.2.jar ~/heap.js
js: var {baz: baz => {}} = ({ [ super
js: ..........................^
js: "/home/rahul/heap.js", line 2: syntax error
js: ] :
js: ..^
js: "/home/rahul/heap.js", line 4: syntax error
js: } ,
js: ^
js: "/home/rahul/heap.js", line 5: syntax error
js: ...
js: ..^
java.lang.OutOfMemoryError: Java heap space
        at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3068)
        at org.mozilla.javascript.Parser.memberExpr(Parser.java:2631)
        at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2529)
        at org.mozilla.javascript.Parser.mulExpr(Parser.java:2454)
        at org.mozilla.javascript.Parser.addExpr(Parser.java:2438)
        at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2419)
        at org.mozilla.javascript.Parser.relExpr(Parser.java:2394)
        at org.mozilla.javascript.Parser.eqExpr(Parser.java:2366)
        at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2355)
        at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2344)
        at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2333)
        at org.mozilla.javascript.Parser.andExpr(Parser.java:2322)
        at org.mozilla.javascript.Parser.orExpr(Parser.java:2311)
        at org.mozilla.javascript.Parser.condExpr(Parser.java:2275)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2238)
        at org.mozilla.javascript.Parser.expr(Parser.java:2217)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
        at org.mozilla.javascript.Parser.statement(Parser.java:1098)
        at org.mozilla.javascript.Parser.parse(Parser.java:642)
        at org.mozilla.javascript.Parser.parse(Parser.java:577)
        at org.mozilla.javascript.Context.compileImpl(Context.java:2512)
        at org.mozilla.javascript.Context.compileString(Context.java:1497)
        at org.mozilla.javascript.Context.compileString(Context.java:1486)
        at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:595)
        at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:560)
        at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:531)
        at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:179)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:100)
        at org.mozilla.javascript.Context.call(Context.java:526)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:509)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:161)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:136)
js: exception from uncaught JavaScript throw: java.lang.OutOfMemoryError: Java heap space
```

**Comment by p-bakker** [comment]
V8 throws a `SyntaxError: Invalid destructuring assignment target`

**Comment by MushyMiddle** [comment]
We just ran into a version of this using this code (also on 1.7.7.2):

`var func = function () {
);`

**Comment by MushyMiddle** [comment]
Never mind - I think.  I downloaded and tested the snipped above on 1.7.13, and received syntax errors, as expected:

```
$ java -Xmx256M -jar ../../rhino-1.7.13.jar killit.js 
js: "killit.js", line 2: syntax error
js: );
js: ^
js: "killit.js", line 2: missing } after function body
js: );
js: .^
js: "killit.js", line 1: Compilation produced 2 syntax errors.
```

**Comment by gbrail** [comment]
I'm going to close this then, if as you say it's fixed in the latest code. Thanks for checking!
