### ISSUE TITLE
ClassCastException in Node.getString

### ISSUE THREAD

**Issue by jon-bell** [mozilla/rhino#662]
We ran into an unexpected ClassCastException when attempting to compile the following string using Rhino 1.7.12: `["".h]=y`

Output:
```Exception in thread "main" java.lang.ClassCastException: org.mozilla.javascript.ast.StringLiteral cannot be cast to org.mozilla.javascript.ast.Name
	at org.mozilla.javascript.Node.getString(Node.java:537)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2262)
	at org.mozilla.javascript.optimizer.BodyCodegen.visitSetProp(Codegen.java:5132)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2610)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2309)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2807)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2309)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateExpression(Codegen.java:2807)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:2059)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1870)
	at org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(Codegen.java:1292)
	at org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:307)
	at org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:166)
	at org.mozilla.javascript.optimizer.Codegen.compile(Codegen.java:75)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2551)
	at org.mozilla.javascript.Context.compileString(Context.java:1507)
	at org.mozilla.javascript.Context.compileString(Context.java:1496)
	at edu.berkeley.cs.jqf.examples.rhino.CompilerTest.main(CompilerTest.java:123)
```

**Comment by rbri** [comment]
Can you please prepare a simple test case to make it easy for us to reproduce this.

You  can have a look at the packages org.mozilla.javascript.tests.es5 or org.mozilla.javascript.tests.es6 for sample tests.

**Comment by p-bakker** [comment]
You sure those double dots (`..`) are correct in your examples? As I think that makes it E4X-specific syntax and thus completely different codePaths, no?

**Comment by tuchida** [comment]
Yes. The first dot is a decimal point. The second dot is a member operator.
http://adripofjavascript.com/blog/drips/numbers-and-javascripts-dot-notation.html

**Comment by p-bakker** [comment]
> es. The first dot is a decimal point. The second dot is a member operator.

Right... learned something new about JavaScript :-)

**Comment by rbri** [comment]
Have done some test cases for this in  #1744. All three cases mentioned by @tuchida and @jon-bell passing with the current code base.

I think we can close this if the pr #1744 is merged.

**Comment by rbri** [comment]
https://github.com/mozilla/rhino/pull/1744 is merged.

Thanks @jon-bell for bringing this up.
