### ISSUE TITLE
IllegalArgumentException: Can't transform: 162 when transforming tree while recording comments

### ISSUE THREAD

**Issue by brecht-yperman-tb** [mozilla/rhino#784]
When compiling a simple Javascript with a comment in it, I cannot transform it to a tree

```javascript
/** @responseClass HttpAdapter */
function httpResponse(){}
```

When compiling and transforming
```java    
CompilerEnvirons compilerEnv = new CompilerEnvirons();
compilerEnv.setOptimizationLevel(5);
compilerEnv.setRecordingComments(true);
compilerEnv.setRecordingLocalJsDocComments(true);
compilerEnv.setStrictMode(true);

Parser p = new Parser(compilerEnv);
String testJs;
try (BufferedReader scriptIn = new BufferedReader(new FileReader("testsrc/jstests/withcomments.js"))) {
    testJs = scriptIn.lines().collect(Collectors.joining(System.lineSeparator()));
}
AstRoot ast = p.parse(testJs, "test", 1);
IRFactory irf = new IRFactory(compilerEnv);
ScriptNode tree = irf.transformTree(ast);
```

Throws an exception
```
Exception in thread "main" java.lang.IllegalArgumentException: Can't transform: 162
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:241)
	at org.mozilla.javascript.IRFactory.transformScript(IRFactory.java:1042)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:191)
	at org.mozilla.javascript.IRFactory.transformTree(IRFactory.java:117)
```

This seems to be introduced by https://github.com/mozilla/rhino/pull/465

**Comment by brecht-yperman-tb** [comment]
I suggested a solution in https://github.com/mozilla/rhino/pull/785

**Comment by gbrail** [comment]
Should be fixed with the merge of that PR -- please re-open if that's not the case.
