### ISSUE TITLE
NullPointerException when  exec const in ScriptEngine

### ISSUE THREAD

**Issue by zfyq124** [mozilla/rhino#798]
exec const in  ScriptEngine, a NullPointerException throw

#### version
1.7.13

#### command
no

#### testcase
```java 
    public void testRhinoExec() throws ScriptException {
        ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine scriptEngine = manager.getEngineByName("rhino");
        Bindings bindings = scriptEngine.createBindings();
        CompiledScript compiledScript = ((Compilable) scriptEngine).compile("const a = 10;");
        Object o = compiledScript.eval(bindings);
        System.out.println(o);
    }
```
#### output

```java
java.lang.NullPointerException
	at com.perfma.xocean.jmeter.JMeterRunner.testRhinoExec(JMeterRunner.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

```

#### expected output
```java
exec success
```

**Comment by zfyq124** [comment]
the reason is for const variable set call org.mozilla.javascript.ScriptableObject#putConst, but get call org.mozilla.javascript.engine.BindingsObject#get can not get the set value

**Comment by p-bakker** [comment]
Could you provide the stacktrace that includes the trace writing the Rhino codebase?

**Comment by tonygermano** [comment]
@p-bakker is this what you're looking for?
It doesn't throw the exception when the script is `var a = 10`, but returns undefined instead. I ran this against the latest snapshot, but haven't looked at the source yet.

```
Caused by: java.lang.NullPointerException
	at org.mozilla.javascript.ScriptableObject.getBase(ScriptableObject.java:2342)
	at org.mozilla.javascript.ScriptableObject.putConstProperty(ScriptableObject.java:2192)
	at org.mozilla.javascript.ScriptRuntime.setConst(ScriptRuntime.java:2154)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1526)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1053)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:124)
	at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:171)
	at org.mozilla.javascript.engine.RhinoCompiledScript.eval(RhinoCompiledScript.java:26)
	at javax.script.CompiledScript.eval(CompiledScript.java:92)
```

**Comment by p-bakker** [comment]
Yeah, wanna check this against the other null pointer cases I've created recently

Tnx for adding!

**Comment by p-bakker** [comment]
@tonygermano any idea if this is just when running though the ScriptEngineManager? Or also when calling Rhino directly?

**Comment by Phinner** [comment]
Is there any possible fixes for this issue ?

**Comment by p-bakker** [comment]
Don't think anyone has dug into this one yet. But since you're asking about this issue: could you clarify when you're running into this issue, ideally provide a code sample to reproduce it?

**Comment by Phinner** [comment]
Like @zfyq124 suggested, I think it's due to how the `BindingsObject` is implemented.

For example, with this code :
```java
public class Playground {
  public static void main(String[] args) throws ScriptException {
    RhinoScriptEngineFactory factory = new RhinoScriptEngineFactory();
    ScriptEngine engine = factory.getScriptEngine();

    System.out.println(engine.eval("let i = 3; i"));
    System.out.println(engine.getContext().getBindings(ScriptContext.ENGINE_SCOPE).entrySet());

    System.out.println(engine.eval("var j = 4; j"));
    System.out.println(engine.getContext().getBindings(ScriptContext.ENGINE_SCOPE).entrySet());

    System.out.println(engine.eval("const k = 5; k"));
    System.out.println(engine.getContext().getBindings(ScriptContext.ENGINE_SCOPE).entrySet());
  }
}
```
The output is :
```java
3
[i=3]
4
[i=3, j=4]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.mozilla.javascript.Scriptable.has(String, org.mozilla.javascript.Scriptable)" because "obj" is null
	at org.mozilla.javascript.ScriptableObject.getBase(ScriptableObject.java:2370)
	at org.mozilla.javascript.ScriptableObject.putConstProperty(ScriptableObject.java:2220)
	at org.mozilla.javascript.ScriptRuntime.setConst(ScriptRuntime.java:2158)
	at org.mozilla.javascript.gen.eval_3._c_script_0(eval:0)
	at org.mozilla.javascript.gen.eval_3.call(eval)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868)
	at org.mozilla.javascript.gen.eval_3.call(eval)
	at org.mozilla.javascript.gen.eval_3.exec(eval)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1137)
	at fr.xpdustry.playground.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:113)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	at fr.xpdustry.playground.Playground.main(Playground.java:21)
```
As expected, the `Bindings` of `BindingsObject` stores the local values but when `const` is used, it just throws a NPM.

**Comment by kopfsport** [comment]
I had some failing Tests using the ScriptEngine Interface after updating to the current version of Rhino, so I was looking for similar problems. My assumption so far is that wrapping and unwrapping of Java Objects is swapped in in the BindingsObject.

```
public class BindingsExample {
    public static class TestClass {
        public String test;
    }

    public static void main(String[] args) throws ScriptException {
        RhinoScriptEngineFactory factory = new RhinoScriptEngineFactory();
        ScriptEngine engine = factory.getScriptEngine();
        engine.getContext().setAttribute("test", new TestClass(), ScriptContext.ENGINE_SCOPE);
        engine.eval("typeof test");
    }
}
```
Results in 

```
Exception in thread "main" javax.script.ScriptException: Invalid JavaScript value of type de.his.core.scripting.BindingsExample$TestClass in eval at line number 0 at column number 0
	at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:136)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at de.his.core.scripting.BindingsExample.main(BindingsExample.java:40)
```

Swapping Context.jsToJava and Context.javaToJS in class BindingsObject makes it work (again).
